### PR TITLE
Added visual representation of the graph to the SceneView

### PR DESCRIPTION
**Pull request by forestrf**
This commit show the graph on the Scene View, but to not flood it, only selected GameObjects or Events that were recently triggered are shown in it.
There are also some random fix in the code. I'm sorry but the code does not respect the original coding format, but I tried to change as less code as possible to keep the git story clean.
The performance may not be good, but that can be optimized later (even though I don't know how much).

Here is a preview of what this pr brings https://streamable.com/x0ips

Thank you

### CODE REVIEW

**Comment by MephestoKhaan** [comment]
This is amazing. I really wanted to add something like this! I am on holidays with my phone right now but will review and merge as soon as possible.

Thanks!

**Comment by forestrf** [comment]
That was the last commit, I'm happy with how it works for now.

**Comment by MephestoKhaan** [comment]
checking this out and getting it ready for the merge :)
Thanks again, you won't believe how happy this made me. Do you have a twitter handle?

**Comment by MephestoKhaan** [comment]
Fixed simply with:

```
			
#if NET_4_6
			var objects = AppDomain.CurrentDomain.GetAssemblies().Where(a => !a.IsDynamic)
				.SelectMany(a => a.GetTypes())
				.Where(t => typeof(Component).IsAssignableFrom(t));
#else
			var objects = AppDomain.CurrentDomain.GetAssemblies()
				.SelectMany(a => a.GetTypes())
				.Where(t => typeof(Component).IsAssignableFrom(t));
#endif
```
it will be a bit slower on 3.X but works very well

**Comment by forestrf** [comment]
I didn't check this with C# 3.5, I forgot. I'm relieved that that was the only problem when not using C# 4 :sweat_drops: 
This is my twitter https://twitter.com/ashkatchap
When I saw this library I noticed just how powerful it can be to make UnityEvents usable and not a mess where you don't know what is happening. After that, I decided that it would be better to also use UnityEvents as a sort of wiring system (like the one in the Unity asset 3D Game Kit) so see the connections in the scene was the goal.

Without you having done this I wouldn't have made the scene view :hugs:

**Pull request merged**
